# Generated by Django 4.2.2 on 2023-06-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_empleado_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='kilometraje',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
