# Generated by Django 4.2.1 on 2023-06-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_servicio_kilometraje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(),
        ),
    ]
